name: flutter_markdown
author: Flutter Authors <flutter-dev@googlegroups.com>
description: A Markdown renderer for Flutter.
homepage: https://github.com/flutter/flutter_markdown
version: 0.2.0

dependencies:
  flutter_web: any

  markdown: ^2.0.0
  meta: ^1.0.5
  string_scanner: ^1.0.0
  path: ^1.5.1

dev_dependencies:
  flutter_web_test: any

  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0

  test: ^1.3.4

  mockito: ^3.0.0

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
